# Generated by Django 4.2.1 on 2024-06-10 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='cats.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='cat',
            name='owners',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='cats.owners', verbose_name='Владельцы'),
        ),
        migrations.AddField(
            model_name='cat',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='cats.tagposts', verbose_name='Тэги'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['-time_create'], name='cats_cat_time_cr_044b61_idx'),
        ),
    ]
