# Generated by Django 4.2.1 on 2024-04-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_cat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='img',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
