# Generated by Django 4.2.1 on 2024-04-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
