# Generated by Django 4.2.1 on 2024-05-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_category_cat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.category'),
        ),
    ]
