# Generated by Django 4.2.1 on 2024-05-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_tagposts_alter_cat_category_cat_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='owners',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='cats.owners'),
        ),
    ]
